import { requireServiceActor } from "@/lib/api/actor";
import { domainCommandsEnabledForTenant } from "@/lib/api/config";
import { apiResponse, createRequestIdentity } from "@/lib/api/http";
import { bindAuthenticatedRequestIdentity } from "@/modules/platform-contracts/requestIdentity";
import { ORDER_FULFILLMENT_CONTRACT_VERSION, parseFulfillmentIntentCommand } from "@/modules/order-fulfillment/contracts";
import { orderFulfillmentRouteFailure, routeId } from "@/modules/order-fulfillment/routeSupport";
import { OrderFulfillmentStore } from "@/modules/order-fulfillment/store";
export const dynamic = "force-dynamic"; export const runtime = "nodejs";
export async function GET(request: Request) { let identity = createRequestIdentity(request.headers); try { const actor = await requireServiceActor(request.headers, "fulfillment_intent.read"); identity = bindAuthenticatedRequestIdentity(identity, actor, { authorityClass: "A0", capability: "fulfillment_intent.read", purpose: "read-bounded-fulfillment-intent", sourceVersionRefs: [ORDER_FULFILLMENT_CONTRACT_VERSION] }); const result = await new OrderFulfillmentStore().readFulfillmentIntent(actor, routeId(new URL(request.url).searchParams.get("fulfillmentIntentId"), "fulfillmentIntentId")); return result ? apiResponse({ ok: true, result }, { requestIdentity: identity }) : apiResponse({ ok: false, code: "FULFILLMENT_INTENT_NOT_FOUND", message: "Fulfillment Intent not found." }, { requestIdentity: identity, status: 404 }); } catch (error) { return orderFulfillmentRouteFailure(error, identity); } }
export async function POST(request: Request) { let identity = createRequestIdentity(request.headers); try { const actor = await requireServiceActor(request.headers, "fulfillment_intent.command"); if (!domainCommandsEnabledForTenant(actor.tenantId)) return apiResponse({ ok: false, code: "DOMAIN_MUTATIONS_DISABLED", message: "Fulfillment Intent mutations remain default-off until an authorized tenant/cohort cutover." }, { requestIdentity: identity, status: 503 }); const command = parseFulfillmentIntentCommand(await request.json()); identity = bindAuthenticatedRequestIdentity(identity, actor, { authorityClass: "A1", capability: "fulfillment_intent.command", idempotencyKey: command.idempotencyKey, purpose: "record-no-effect-fulfillment-intent", sourceVersionRefs: [ORDER_FULFILLMENT_CONTRACT_VERSION, command.expectedObjectVersion] }); const result = await new OrderFulfillmentStore().executeFulfillmentIntent({ actor, command, correlationId: identity.correlationId, requestedAt: identity.requestedAt }); return apiResponse({ ok: true, result }, { requestIdentity: identity, status: result.receipt.idempotentReplay ? 200 : 201 }); } catch (error) { return orderFulfillmentRouteFailure(error, identity); } }
