import {
  OPERATIONS_EVIDENCE_LEDGER_V3_AUXILIARY_VERSIONS,
  OPERATIONS_EVIDENCE_LEDGER_V3_MANIFEST_VERSION,
  OPERATIONS_EVIDENCE_LEDGER_V3_VERSION,
} from "./contracts";
import {
  calculateCapabilityEpochResetDigest,
  calculateCanonicalSourceAttestationDigest,
  calculateExactSourceBytesHash,
  calculateG2EffectAuthorityGrantDigest,
  calculateHumanAuthoritySourceBindingDigest,
  calculateIncidentRecoverySourceBindingDigest,
  calculateOperationsEvidenceLedgerV3Digest,
  calculateOperationsEvidenceAppendStateDigest,
  calculateOperationsEvidenceAppendStateDigestV2,
  calculateStableSignedSourceReadbackIdentityDigest,
  calculateSourceSnapshotDigest,
  createGenesisOperationsEvidenceAppendStateV1,
  createInMemoryOperationsEvidenceAppendStateStoreV1,
  createGenesisOperationsEvidenceAppendStateV2,
  createInMemoryOperationsEvidenceAppendStateStoreV2,
  deriveCapabilityEpochResetV2,
  parseLuzioneOperationsEvidenceLedgerManifestV3,
  parseOperationsEvidenceAppendStateV1,
  parseOperationsEvidenceAppendStateV2,
  parseStableSignedSourceReadbackIdentityV1,
  reinitializeEmptySyntheticAppendStateV1AsV2,
  parseOperationsEvidenceLedgerV3,
  sealG2EffectAuthorityGrantV2,
  sealHumanAuthoritySourceBindingV1,
  sealIncidentRecoverySourceBindingV1,
  sealOperationsEvidenceLedgerV3,
} from "./sdk";
import { OPS_CORRECTION_04_ASSURANCE, OPS_CORRECTION_04_ADVERSE_PROBES, OPS_LEDGER_V3_SCHEMA_KEYS, OPS_V3_SYNTHETIC_SOURCE_TRUST_ROOT, REQUIRED_G2_SCOPES_V2 } from "./rules";

export const luzioneOperationsEvidenceLedgerSdkV3 = Object.freeze({
  adverseProbes: OPS_CORRECTION_04_ADVERSE_PROBES,
  assurance: OPS_CORRECTION_04_ASSURANCE,
  auxiliaryVersions: OPERATIONS_EVIDENCE_LEDGER_V3_AUXILIARY_VERSIONS,
  calculateCapabilityEpochResetDigest,
  calculateCanonicalSourceAttestationDigest,
  calculateExactSourceBytesHash,
  calculateG2EffectAuthorityGrantDigest,
  calculateHumanAuthoritySourceBindingDigest,
  calculateIncidentRecoverySourceBindingDigest,
  calculateAppendStateDigestV1: calculateOperationsEvidenceAppendStateDigest,
  calculateAppendStateDigest: calculateOperationsEvidenceAppendStateDigestV2,
  calculateStableSignedSourceReadbackIdentityDigest,
  calculateLedgerDigest: calculateOperationsEvidenceLedgerV3Digest,
  calculateSourceSnapshotDigest,
  createGenesisAppendStateV1: createGenesisOperationsEvidenceAppendStateV1,
  createInMemoryAppendStateStoreV1: createInMemoryOperationsEvidenceAppendStateStoreV1,
  createGenesisAppendState: createGenesisOperationsEvidenceAppendStateV2,
  createInMemoryAppendStateStore: createInMemoryOperationsEvidenceAppendStateStoreV2,
  deriveCapabilityEpochReset: deriveCapabilityEpochResetV2,
  ledgerVersion: OPERATIONS_EVIDENCE_LEDGER_V3_VERSION,
  manifestVersion: OPERATIONS_EVIDENCE_LEDGER_V3_MANIFEST_VERSION,
  parseLedger: parseOperationsEvidenceLedgerV3,
  parseManifest: parseLuzioneOperationsEvidenceLedgerManifestV3,
  parseAppendStateV1: parseOperationsEvidenceAppendStateV1,
  parseAppendState: parseOperationsEvidenceAppendStateV2,
  parseStableSignedSourceReadbackIdentity: parseStableSignedSourceReadbackIdentityV1,
  reinitializeEmptySyntheticAppendStateV1AsV2,
  requiredG2Scopes: REQUIRED_G2_SCOPES_V2,
  schemaKeys: OPS_LEDGER_V3_SCHEMA_KEYS,
  syntheticSourceTrustRoot: OPS_V3_SYNTHETIC_SOURCE_TRUST_ROOT,
  sealG2Grant: sealG2EffectAuthorityGrantV2,
  sealHumanBinding: sealHumanAuthoritySourceBindingV1,
  sealIncidentRecovery: sealIncidentRecoverySourceBindingV1,
  sealLedger: sealOperationsEvidenceLedgerV3,
});
