import assert from "node:assert/strict";
import { Pool } from "pg";

import type { ApiActor } from "@/lib/api/actor";
import type { HumanApprovalSubject } from "@/modules/onboard-core/humanApproval";
import { HUMAN_APPROVAL_SUBJECT_VERSION } from "@/modules/onboard-core/humanApproval";
import { IdempotencyConflictError } from "@/modules/platform-guarantees/commandKernel";
import { SEED_PROCUREMENT_COMMAND_VERSION, parseSeedProcurementCommand, type EvidenceArtifactRegisterCommand } from "@/modules/seed-procurement/contracts";
import { SeedProcurementStore } from "@/modules/seed-procurement/store";
import { SUPPLIER_PROFILE_COMMAND_VERSION, parseSeedSupplierIdentityCommand, type SupplierProfileFacts, type SupplierProfileProposeCommand, type SupplierProfileReviseCommand } from "@/modules/seed-supplier-identity/contracts";
import { portalAccountAccessBindingId, portalAccountAccessBindingVersion, parsePortalAccountAccessBindingCommand, requirePortalAccountAccess } from "@/modules/seed-supplier-identity/portalAccessContracts";
import { PortalAccountAccessBindingStore } from "@/modules/seed-supplier-identity/portalAccessBinding";
import { accountVersionRef, supplierProfileIdFor } from "@/modules/seed-supplier-identity/model";
import { SeedSupplierIdentityDomainError, SeedSupplierIdentityStore } from "@/modules/seed-supplier-identity/store";

const connectionString=process.env.DATABASE_URL; if(!connectionString) throw new Error("DATABASE_URL is required.");
const pool=new Pool({connectionString}); const tenantId="tenant-proof-a";
const transport:ApiActor={actorId:"service:luzione-ui",actorType:"service",capabilities:["supplier.profile.command","supplier.profile.read"],source:"service-token",tenantId};
const portalTransport:ApiActor={actorId:"service:luzione-supplier-portal",actorType:"service",capabilities:["supplier.portal.account_binding.command","supplier.portal.account_binding.read"],source:"service-token",tenantId};
function human(actorId:string,capabilities:string[]):HumanApprovalSubject{return {actorId,actorType:"user",authenticationRef:`supabase-session:${actorId}`,authenticatedAt:"2026-09-05T09:00:00.000Z",capabilities,contractVersion:HUMAN_APPROVAL_SUBJECT_VERSION,source:"supabase-user-jwt",tenantId};}
const proposer=human("user-proposer",["supplier.profile.propose","supplier.profile.revise"]); const approver=human("user-approver",["supplier.profile.activate","supplier.profile.archive","supplier.profile.expire","supplier.profile.revoke","supplier.profile.suspend","supplier.portal.account_binding.record","supplier.portal.account_binding.revoke"]); const otherApprover=human("user-approver-other",["supplier.profile.activate"]);
const at={evidence:"2026-09-05T09:20:00.000Z",propose:"2026-09-05T09:30:00.000Z",activate:"2026-09-05T09:31:00.000Z",later:"2026-09-05T09:32:00.000Z"};
function profileId(accountId:string){return supplierProfileIdFor(tenantId,accountId);}
function evidenceCommand(){return parseSeedProcurementCommand({artifact:{capturedAt:at.evidence,confidence:1,contentDigest:"a".repeat(64),kind:"UPLOAD",mimeType:"application/pdf",promptInjectionState:"CLEAR",provider:"OPERATOR_UPLOAD",sourceRecordRef:"supplier-proof-evidence",storageRef:"private-object:supplier-proof-evidence"},commandId:"supplier-proof-evidence",commandType:"evidence_artifact.register",contractVersion:SEED_PROCUREMENT_COMMAND_VERSION,expectedVersion:"ABSENT",idempotencyKey:"supplier-proof-evidence-idem",projectRef:null}) as EvidenceArtifactRegisterCommand;}
function facts(ref:{objectId:string;version:string},conflict=false):SupplierProfileFacts{return {approvedCategories:["casegoods"],approvedRegions:["US-CA"],capabilities:["CATALOG_SOURCE","PO_ACKNOWLEDGEMENT","QUOTE_SUBMISSION","RFQ_RESPONSE"],contactRefs:[],evidenceRefs:[{objectId:ref.objectId,objectType:"EVIDENCE_ARTIFACT",ownerProject:"LUZIONE_PROCUREMENT",version:ref.version}],identityReview:{conflictRefs:conflict?["identity-conflict-1"]:[],duplicateAccountRefs:[]},provenanceRefs:["operator-review:supplier-proof"],validFrom:"2026-09-05T09:00:00.000Z",validUntil:"2026-10-05T09:00:00.000Z"};}
function propose(accountId:string,ref:{objectId:string;version:string},suffix=accountId,conflict=false){return parseSeedSupplierIdentityCommand({accountId,accountVersion:accountVersionRef(accountId,1),commandId:`supplier-propose-${suffix}`,commandType:"supplier_profile.propose",contractVersion:SUPPLIER_PROFILE_COMMAND_VERSION,expectedVersion:"ABSENT",idempotencyKey:`supplier-propose-${suffix}-idem`,profile:facts(ref,conflict)}) as SupplierProfileProposeCommand;}
function revise(accountId:string,expectedVersion:string,ref:{objectId:string;version:string}){return parseSeedSupplierIdentityCommand({accountId,accountVersion:accountVersionRef(accountId,1),commandId:`supplier-revise-${accountId}`,commandType:"supplier_profile.revise",contractVersion:SUPPLIER_PROFILE_COMMAND_VERSION,expectedVersion,idempotencyKey:`supplier-revise-${accountId}-idem`,profile:facts(ref),supplierProfileId:profileId(accountId)}) as SupplierProfileReviseCommand;}
function transition(id:string,expectedVersion:string,ref:{objectId:string;version:string},action:"ACTIVATE"|"EXPIRE"|"SUSPEND"|"REVOKE",suffix:string){return parseSeedSupplierIdentityCommand({action,commandId:`supplier-${action.toLowerCase()}-${suffix}`,commandType:"supplier_profile.transition",contractVersion:SUPPLIER_PROFILE_COMMAND_VERSION,evidenceRefs:[{objectId:ref.objectId,objectType:"EVIDENCE_ARTIFACT",ownerProject:"LUZIONE_PROCUREMENT",version:ref.version}],expectedVersion,idempotencyKey:`supplier-${action.toLowerCase()}-${suffix}-idem`,reason:`Proof ${action.toLowerCase()}.`,supplierProfileId:id});}
function code(error:unknown){return error instanceof SeedSupplierIdentityDomainError?error.code:String(error);}
async function tenantQuery<T>(sql:string,values:unknown[]=[]){const client=await pool.connect();try{await client.query("begin read only");await client.query("select set_config('app.tenant_id',$1,true)",[tenantId]);const result=await client.query(sql,values);await client.query("commit");return result.rows as T[];}catch(error){await client.query("rollback");throw error;}finally{client.release();}}

async function main(){try{
  const procurement=new SeedProcurementStore(pool); const evidence=await procurement.executeEvidence({actor:{...transport,capabilities:["procurement.command","procurement.read"]},command:evidenceCommand(),correlationId:"supplier-evidence-correlation",requestedAt:at.evidence}); const ref={objectId:evidence.readback.resource.id,version:evidence.readback.resource.version};
  const store=new SeedSupplierIdentityStore(pool); const primary=propose("supplier-profile-primary",ref);
  await assert.rejects(store.execute({actor:{...transport,actorType:"user"},command:primary,correlationId:"supplier-forged-transport",human:proposer,requestedAt:at.propose}),(error:unknown)=>code(error)==="SUPPLIER_PROFILE_TRANSPORT_AUTHORITY_REQUIRED");
  await assert.rejects(store.execute({actor:{...transport,capabilities:["supplier.profile.read"]},command:primary,correlationId:"supplier-missing-capability",human:proposer,requestedAt:at.propose}),(error:unknown)=>code(error)==="SUPPLIER_PROFILE_TRANSPORT_AUTHORITY_REQUIRED");
  await assert.rejects(store.execute({actor:transport,command:primary,correlationId:"supplier-invalid-requested-at",human:proposer,requestedAt:"2026-09-05 09:30:00"}),(error:unknown)=>code(error)==="INVALID_REQUESTED_AT");
  await assert.rejects(store.readById(transport,profileId("supplier-profile-primary"),"2026-02-30T09:30:00.000Z"),(error:unknown)=>code(error)==="INVALID_OBSERVED_AT");
  const proposed=await store.execute({actor:transport,command:primary,correlationId:"supplier-propose-correlation",human:proposer,requestedAt:at.propose}); assert.equal(proposed.readback.supplierProfile.resource.status,"PROPOSED"); assert.equal(proposed.readback.timelineEvent.receipt.receiptId,proposed.receipt.receiptId);
  const replay=await new SeedSupplierIdentityStore(pool).execute({actor:transport,command:primary,correlationId:"supplier-propose-replay",human:proposer,requestedAt:at.propose}); assert.equal(replay.receipt.idempotentReplay,true); assert.equal(replay.receipt.receiptId,proposed.receipt.receiptId); assert.equal(replay.readback.supplierProfile.createdAt,proposed.readback.supplierProfile.createdAt);
  await assert.rejects(store.execute({actor:transport,command:{...primary,profile:{...primary.profile,approvedRegions:["US-NY"]}},correlationId:"supplier-propose-changed",human:proposer,requestedAt:at.propose}),IdempotencyConflictError);
  const activate=transition(profileId("supplier-profile-primary"),proposed.receipt.objectVersion,ref,"ACTIVATE","primary");
  await assert.rejects(store.execute({actor:transport,command:activate,correlationId:"supplier-self-approve",human:{...proposer,capabilities:[...proposer.capabilities,"supplier.profile.activate"]},requestedAt:at.activate}),(error:unknown)=>code(error)==="PORTAL_SELF_APPROVAL_DENIED");
  const activated=await store.execute({actor:transport,command:activate,correlationId:"supplier-activate",human:approver,requestedAt:at.activate}); assert.equal(activated.readback.supplierProfile.resource.status,"ELIGIBLE"); assert.equal(activated.readback.supplierProfile.authority.decision,"REQUIRE_HUMAN");
  assert.equal((await store.requireEligible(transport,"supplier-profile-primary","RFQ_RESPONSE",at.later)).resource.status,"ELIGIBLE");
  await assert.rejects(store.requireEligible(transport,"supplier-profile-primary","FULFILLMENT_UPDATE",at.later),(error:unknown)=>code(error)==="SUPPLIER_NOT_ELIGIBLE");
  await assert.rejects(store.requireEligible(transport,"supplier-profile-primary","RFQ_RESPONSE","2026-10-05T09:00:00.000Z"),(error:unknown)=>code(error)==="SUPPLIER_NOT_ELIGIBLE");
  const suspended=await store.execute({actor:transport,command:transition(profileId("supplier-profile-primary"),activated.receipt.objectVersion,ref,"SUSPEND","primary"),correlationId:"supplier-suspend",human:approver,requestedAt:at.later}); assert.equal(suspended.readback.supplierProfile.resource.status,"SUSPENDED"); await assert.rejects(store.requireEligible(transport,"supplier-profile-primary","RFQ_RESPONSE",at.later));
  const expired=await store.execute({actor:transport,command:transition(profileId("supplier-profile-primary"),suspended.receipt.objectVersion,ref,"EXPIRE","primary"),correlationId:"supplier-expire",human:approver,requestedAt:"2026-10-05T09:00:00.000Z"}); assert.equal(expired.readback.supplierProfile.resource.status,"EXPIRED"); await assert.rejects(store.requireEligible(transport,"supplier-profile-primary","RFQ_RESPONSE","2026-10-05T09:00:00.000Z"));
  const revokedProfile=await store.execute({actor:transport,command:transition(profileId("supplier-profile-primary"),expired.receipt.objectVersion,ref,"REVOKE","primary"),correlationId:"supplier-revoke",human:approver,requestedAt:"2026-10-05T09:00:01.000Z"}); assert.equal(revokedProfile.readback.supplierProfile.resource.status,"REVOKED"); await assert.rejects(store.requireEligible(transport,"supplier-profile-primary","RFQ_RESPONSE","2026-10-05T09:00:01.000Z"));
  assert.equal(await new SeedSupplierIdentityStore(pool).readById({...transport,tenantId:"tenant-proof-b"},profileId("supplier-profile-primary")),null);
  await assert.rejects(store.execute({actor:transport,command:propose("missing-account",ref),correlationId:"supplier-missing",human:proposer,requestedAt:at.propose}),(error:unknown)=>code(error)==="SUPPLIER_ACCOUNT_NOT_FOUND");
  const conflict=await store.execute({actor:transport,command:propose("supplier-profile-conflict",ref,"conflict",true),correlationId:"supplier-conflict-propose",human:proposer,requestedAt:at.propose}); await assert.rejects(store.execute({actor:transport,command:transition(profileId("supplier-profile-conflict"),conflict.receipt.objectVersion,ref,"ACTIVATE","conflict"),correlationId:"supplier-conflict-activate",human:approver,requestedAt:at.activate}),(error:unknown)=>code(error)==="INVALID_SUPPLIER_TRANSITION");
  const concurrentProposal=await store.execute({actor:transport,command:propose("supplier-profile-concurrent",ref),correlationId:"supplier-concurrent-propose",human:proposer,requestedAt:at.propose}); const concurrentCommand=transition(profileId("supplier-profile-concurrent"),concurrentProposal.receipt.objectVersion,ref,"ACTIVATE","concurrent-a"); const results=await Promise.allSettled([store.execute({actor:transport,command:concurrentCommand,correlationId:"supplier-concurrent-a",human:approver,requestedAt:at.activate}),store.execute({actor:transport,command:{...concurrentCommand,commandId:"supplier-activate-concurrent-b",idempotencyKey:"supplier-activate-concurrent-b-idem"},correlationId:"supplier-concurrent-b",human:otherApprover,requestedAt:at.activate})]); assert.equal(results.filter(item=>item.status==="fulfilled").length,1); assert.equal(results.filter(item=>item.status==="rejected"&&code(item.reason)==="VERSION_CONFLICT").length,1);
  const faultCommand=propose("supplier-profile-fault",ref); const faultStore=new SeedSupplierIdentityStore(pool,{afterOwnerWrite:async()=>{throw new Error("PROOF_FAULT_AFTER_OWNER_WRITE");}}); await assert.rejects(faultStore.execute({actor:transport,command:faultCommand,correlationId:"supplier-fault",human:proposer,requestedAt:at.propose}),/PROOF_FAULT/); const faults=await tenantQuery<{owners:string;receipts:string}>(`select (select count(*)::text from public.seed_supplier_profile_versions where supplier_profile_id=$1) owners,(select count(*)::text from public.p110_command_receipts where command_id=$2) receipts`,[profileId("supplier-profile-fault"),faultCommand.commandId]); assert.deepEqual(faults[0],{owners:"0",receipts:"0"});
  const revisionProposal=await store.execute({actor:transport,command:faultCommand,correlationId:"supplier-revision-propose",human:proposer,requestedAt:"2026-09-05T09:35:00.000Z"});
  const revisionActivated=await store.execute({actor:transport,command:transition(profileId("supplier-profile-fault"),revisionProposal.receipt.objectVersion,ref,"ACTIVATE","revision"),correlationId:"supplier-revision-activate",human:approver,requestedAt:"2026-09-05T09:36:00.000Z"});
  const revised=await store.execute({actor:transport,command:revise("supplier-profile-fault",revisionActivated.receipt.objectVersion,ref),correlationId:"supplier-revision",human:proposer,requestedAt:"2026-09-05T09:37:00.000Z"});
  const revisedLatest=await store.readById(transport,profileId("supplier-profile-fault")); assert.ok(revisedLatest); assert.equal(revised.readback.supplierProfile.createdAt,revisionProposal.readback.supplierProfile.createdAt); assert.equal(revisedLatest.createdAt,revisionProposal.readback.supplierProfile.createdAt); assert.equal(revisedLatest.resource.version,revised.readback.supplierProfile.resource.version);
  const organizationId="portal-org-proof"; const bindingId=portalAccountAccessBindingId(tenantId,organizationId,"supplier-profile-primary"); const membership={id:"membership-proof",status:"ACTIVE" as const,version:"membership:membership-proof:v1"}; const grant={id:"grant-proof",status:"ACTIVE" as const,version:"grant:grant-proof:v1"}; const portalRecord=parsePortalAccountAccessBindingCommand({accountId:"supplier-profile-primary",accountVersion:accountVersionRef("supplier-profile-primary",1),bindingId,commandId:"portal-binding-record",commandType:"portal_account_access_binding.record",contractVersion:"PortalOrganizationAccountAccessBindingCommand/v1",evidenceRefs:[{...ref,objectType:"EVIDENCE_ARTIFACT",ownerProject:"LUZIONE_PROCUREMENT"}],expectedVersion:"ABSENT",idempotencyKey:"portal-binding-record-idem",membershipRef:membership,objectGrantRef:grant,organizationId}); const portalStore=new PortalAccountAccessBindingStore(pool);
  await assert.rejects(portalStore.execute({actor:{...portalTransport,actorId:"service:forged-portal"},command:portalRecord,correlationId:"portal-binding-forged-workload",human:approver,requestedAt:"2026-09-05T09:33:00.000Z"}),(error:unknown)=>code(error)==="PORTAL_WORKLOAD_IDENTITY_REQUIRED");
  await assert.rejects(portalStore.execute({actor:{...portalTransport,capabilities:["supplier.portal.account_binding.read"]},command:portalRecord,correlationId:"portal-binding-missing-capability",human:approver,requestedAt:"2026-09-05T09:33:00.000Z"}),(error:unknown)=>code(error)==="PORTAL_WORKLOAD_IDENTITY_REQUIRED");
  await assert.rejects(portalStore.execute({actor:portalTransport,command:portalRecord,correlationId:"portal-binding-invalid-requested-at",human:approver,requestedAt:"2026-09-05 09:33:00"}),(error:unknown)=>code(error)==="INVALID_REQUESTED_AT");
  const binding=await portalStore.execute({actor:portalTransport,command:portalRecord,correlationId:"portal-binding-record",human:approver,requestedAt:"2026-09-05T09:33:00.000Z"}); assert.equal(binding.timelineEvent.receipt.receiptId,binding.receipt.receiptId); assert.deepEqual(requirePortalAccountAccess({binding:binding.readback,membershipRef:membership,objectGrantRef:grant,observedTenantId:tenantId,organizationId}),binding.readback.accountRef);
  const conflictingBindingId=portalAccountAccessBindingId(tenantId,organizationId,"supplier-profile-portal-other"); const conflictingPortalRecord=parsePortalAccountAccessBindingCommand({accountId:"supplier-profile-portal-other",accountVersion:accountVersionRef("supplier-profile-portal-other",1),bindingId:conflictingBindingId,commandId:"portal-binding-record-conflict",commandType:"portal_account_access_binding.record",contractVersion:"PortalOrganizationAccountAccessBindingCommand/v1",evidenceRefs:[{...ref,objectType:"EVIDENCE_ARTIFACT",ownerProject:"LUZIONE_PROCUREMENT"}],expectedVersion:"ABSENT",idempotencyKey:"portal-binding-record-conflict-idem",membershipRef:{id:"membership-conflict",status:"ACTIVE",version:"membership:membership-conflict:v1"},objectGrantRef:{id:"grant-conflict",status:"ACTIVE",version:"grant:grant-conflict:v1"},organizationId}); await assert.rejects(portalStore.execute({actor:portalTransport,command:conflictingPortalRecord,correlationId:"portal-binding-record-conflict",human:approver,requestedAt:"2026-09-05T09:33:15.000Z"}),/duplicate key value|unique constraint/i); assert.equal((await tenantQuery<{count:string}>("select count(*)::text count from public.seed_supplier_portal_account_binding_versions where organization_id=$1",[organizationId]))[0].count,"1");
  const swappedRevoke=parsePortalAccountAccessBindingCommand({bindingId,commandId:"portal-binding-revoke-swapped",commandType:"portal_account_access_binding.revoke",contractVersion:"PortalOrganizationAccountAccessBindingCommand/v1",evidenceRefs:[{...ref,objectType:"EVIDENCE_ARTIFACT",ownerProject:"LUZIONE_PROCUREMENT"}],expectedVersion:portalAccountAccessBindingVersion(bindingId,1),idempotencyKey:"portal-binding-revoke-swapped-idem",membershipRef:{id:"membership-swapped",status:"REVOKED",version:"membership:membership-swapped:v2"},objectGrantRef:{...grant,version:"grant:grant-proof:v2"},revocationRef:"portal-revocation-swapped"}); await assert.rejects(portalStore.execute({actor:portalTransport,command:swappedRevoke,correlationId:"portal-binding-revoke-swapped",human:approver,requestedAt:"2026-09-05T09:33:30.000Z"}),(error:unknown)=>code(error)==="PORTAL_BINDING_LINEAGE_CONFLICT");
  const revokedMembership={...membership,status:"REVOKED" as const,version:"membership:membership-proof:v2"}; const advancedGrant={...grant,version:"grant:grant-proof:v2"}; const revoke=parsePortalAccountAccessBindingCommand({bindingId,commandId:"portal-binding-revoke",commandType:"portal_account_access_binding.revoke",contractVersion:"PortalOrganizationAccountAccessBindingCommand/v1",evidenceRefs:[{...ref,objectType:"EVIDENCE_ARTIFACT",ownerProject:"LUZIONE_PROCUREMENT"}],expectedVersion:portalAccountAccessBindingVersion(bindingId,1),idempotencyKey:"portal-binding-revoke-idem",membershipRef:revokedMembership,objectGrantRef:advancedGrant,revocationRef:"portal-revocation-proof"}); const revoked=await portalStore.execute({actor:portalTransport,command:revoke,correlationId:"portal-binding-revoke",human:approver,requestedAt:"2026-09-05T09:34:00.000Z"}); assert.equal(revoked.readback.status,"REVOKED"); assert.throws(()=>requirePortalAccountAccess({binding:revoked.readback,membershipRef:revokedMembership,objectGrantRef:advancedGrant,observedTenantId:tenantId,organizationId}));
  const ledger=await tenantQuery<{bad_effects:string;events:string;receipts:string}>(`select (select count(*)::text from public.p110_command_receipts where command_type like 'supplier_profile.%' or command_type like 'portal_account_access_binding.%') receipts,(select count(*)::text from public.p110_event_envelopes where command_id in (select command_id from public.p110_command_receipts where command_type like 'supplier_profile.%' or command_type like 'portal_account_access_binding.%')) events,(select count(*)::text from public.p110_outbox_messages where receipt_id in (select receipt_id from public.p110_command_receipts where command_type like 'supplier_profile.%' or command_type like 'portal_account_access_binding.%') and effect_class<>'NO_EFFECT') bad_effects`); assert.equal(ledger[0].receipts,ledger[0].events); assert.equal(ledger[0].bad_effects,"0"); assert.equal((await tenantQuery<{bad:string}>("select count(*)::text bad from public.p110_command_receipts where command_type like 'supplier_profile.%' and state<>'DOMAIN_COMMITTED'"))[0].bad,"0");
  console.log(JSON.stringify({atomicityFaultRollback:faults[0],canonicalTimeFailClosed:true,changedReplayDenied:true,concurrentActivationWinner:true,durableTimelineProjection:true,eligibleCapabilityRead:true,ledger:ledger[0],portalAccessBinding:{humanApproved:true,oneOrganizationOneAccountHistory:true,revocationDenied:true,wrongWorkloadDenied:true},portalSelfApprovalDenied:true,profileLifecycle:{expiredDenied:true,revokedDenied:true,revisionCreatedAtPreserved:true},storedStatusNotTimeMutated:true,tenantIsolation:true,transportCapabilityFailClosed:true},null,2));
}finally{await pool.end();}}
void main().catch(error=>{console.error(error);process.exitCode=1;});
